### ISSUE TITLE
WoW Beta: Lua error when setting up officer channel

### ISSUE THREAD

**Issue by Tetsemi** [AIE-Guild/GreenWall#126] opened 2018-04-25 23:40 UTC
I entered the officer password in my Guildmaster Officer Note in the Guild Roster and did a /gw ochat on which showed the message of enabling the channel.  When I sent a test message to the officer channel via /o  I got this error message

`1x GreenWall\Chat-Chat.lua:166: attempt to call global 'SendAddonMessage' (a nil value)
GreenWall\Chat-Chat.lua:166: in function `SendLocal'
GreenWall\Channel-Channel.lua:211: in function `join'
GreenWall\Config.lua:363: in function `refresh_channels'
GreenWall\GreenWall-1.9.0.lua:490: in function <GreenWall\GreenWall.lua:490>
GreenWall\HoldDown.lua:76: in function <GreenWall\HoldDown.lua:71>

Locals:
type = 7
message = "officer"
opcode = "R"
payload = "R#officer"
(*temporary) = nil
(*temporary) = "GreenWall"
(*temporary) = "R#officer"
(*temporary) = "GUILD"
(*temporary) = "attempt to call global 'SendAddonMessage' (a nil value)"
`

**Comment by mrogaski** [comment] 2018-04-26 04:13
Duplicate of #127.

**Closed by mrogaski** 2018-04-26 04:13 UTC
Labels: duplicate
