### ISSUE TITLE
SendChatMessage or tl_flush function error?

### ISSUE THREAD

**Issue by ryooshi** [AIE-Guild/GreenWall#175] opened 2020-03-22 01:00 UTC
Not sure what any of this means, but a guildmate suggested I post this here.  Seems to happen a lot when getting an achievement.

7x [ADDON_ACTION_BLOCKED] AddOn 'GreenWall' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "=[C]"]: in function `SendChatMessage'
[string "@GreenWall\Channel-Channel.lua"]:365: in function `tl_flush'
[string "@GreenWall\Channel-Channel.lua"]:325: in function <GreenWall\Channel.lua:297>
[string "=(tail call)"]: ?
[string "@GreenWall\GreenWall-1.10.1.lua"]:330: in function `GreenWall_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
Skipped (In Encounter)

**Comment by mrogaski** [comment] 2020-03-23 02:26
Do any achievement announcements make it through?

**Comment by ryooshi** [comment] 2020-03-25 20:10
I just got an achievement a second ago, and three members from separate co-guilds confirmed they couldn't see it.  One member in my primary guild did see it, though.

**Comment by mrogaski** [comment] 2020-03-28 06:20
Duplicate of #171

**Closed** 2020-03-28 06:20 UTC
Labels: bug, duplicate
