### ISSUE TITLE
status command reports errors

### ISSUE THREAD

**Issue by ashayo** [AIE-Guild/GreenWall#70] opened 2015-02-21 07:19 UTC
As a cohort:
Date: 2015-02-21 18:15:05
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\GreenWall\Channel.lua line 230:
   bad argument #1 to 'tostring' (value expected)
Debug:
   [C]: ?
   [C]: tostring()
   GreenWall\Channel.lua:230: dump_status()
   GreenWall\Config.lua:127: dump_status()
   GreenWall\GreenWall.lua:202: ?()
   ..\FrameXML\ChatFrame.lua:4387: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4041: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4080: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1

As an officer reports correct output, but then also
GreenWall: [ERROR] true

preceding out
"2015-02-21 18:18:09 -- [debug/5@Channel.lua:116(is_configured)] number=3, name=<<0419>>, password=<<41FB>>, version=1, stale=false", -- [427]
	"2015-02-21 18:18:09 -- [debug/5@Channel.lua:124(is_connected)] number=3, name=<<0419>>", -- [428]
	"2015-02-21 18:18:09 -- [debug/5@Channel.lua:116(is_configured)] number=3, name=<<0419>>, password=<<41FB>>, version=1, stale=false", -- [429]
	"2015-02-21 18:18:09 -- [debug/5@Channel.lua:127(is_connected)] set number=3", -- [430]
	"2015-02-21 18:18:09 -- [debug/5@Channel.lua:116(is_configured)] number=4, name=<<6A72>>, password=<<2D90>>, version=1, stale=false", -- [431]
	"2015-02-21 18:18:09 -- [debug/5@Channel.lua:124(is_connected)] number=4, name=<<6A72>>", -- [432]
	"2015-02-21 18:18:09 -- [debug/5@Channel.lua:116(is_configured)] number=4, name=<<6A72>>, password=<<2D90>>, version=1, stale=false", -- [433]
	"2015-02-21 18:18:09 -- [debug/5@Channel.lua:127(is_connected)] set number=4", -- [434]

**Comment by mrogaski** [comment] 2015-02-21 07:25
Duplicate of #68.

**Closed by mrogaski** 2015-02-21 07:25 UTC
Labels: duplicate
