### ISSUE TITLE
While intoxicated, achievement text is modified and passed through Greenwall

### ISSUE THREAD

**Issue by Tetsemi** [AIE-Guild/GreenWall#84] opened 2015-08-10 17:43 UTC
Don't know if anything can be done about this, or if it's an artifact of the game.  Here is the example I saw today.

[Kyrthor]: A#gravitas##%s hash earned the achievement [250 Quests Completed]! ...hic!

**Comment by mrogaski** [comment] 2015-08-10 19:00
Duplicate of #47.

**Closed by mrogaski** 2015-08-10 19:00 UTC
Labels: bug, duplicate
