### ISSUE TITLE
SendChat error

### ISSUE THREAD

**Issue by yakko51** [AIE-Guild/GreenWall#187] opened 2020-08-09 17:44 UTC
Date: 2020-08-09 08:30:58
ID: 1
Error occured in: AddOn: GreenWall
Count: 1
Message: Warning: AddOn GreenWall attempted to call a protected function (SendChatMessage()) which may require interaction.
Debug:
   [string "=[C]"]: SendChatMessage()
   [string "@GreenWall\Channel.lua"]:365: tl_flush()
   [string "@GreenWall\Channel.lua"]:325:
      GreenWall\Channel.lua:297
   [string "=(tail call)"]: ?
   [string "@GreenWall\GreenWall.lua"]:330: GreenWall_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  Auctioneer, v8.3.BETA-4-4 (NzothsFolly)
  AuctioneerStatsOverTime, v8.3.BETA-4-4 (NzothsFolly)
  AuctioneerUtilDealFinder, v8.3.BETA-4-4 (NzothsFolly)
  AuctioneerUtilValuer, v8.3.BETA-4-4 (NzothsFolly)
  Enchantrix, v8.3.BETA-4-4 (NzothsFolly)
  EnchantrixBarker, v8.3.BETA-4-4 (NzothsFolly)
  FarmHud, v8.3-6-classic-release
  FasterLooting, v1.1.1
  GreenWall, v1.10.1+classic
  Informant, v8.3.BETA-4-4 (NzothsFolly)
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  SlideBar, v8.3.BETA-4-4 (NzothsFolly)
  Stubby, v8.3.BETA-4-4 (NzothsFolly)
  BlizRuntimeLib_enUS v8.3.7.80300 <none>
  (ck=28f)

**Comment by mrogaski** [comment] 2020-08-10 03:25
Duplicate of #171 .

**Closed by mrogaski** 2020-08-10 03:25 UTC
Labels: duplicate
